import = [
"~/.config/alacritty/colors.toml",
"~/.config/alacritty/fonts.toml",
]

[shell]
program = "/bin/zsh"
args = ["-l"]

[window]
position = { x = 0, y = 0 }
padding = { x = 12, y = 12}
decorations = "Buttonless"
startup_mode = "Maximized"
opacity = 1
title = "cfsanderson"

[scrolling]
history = 10000
multiplier = 3

[cursor]
style = { shape = "Block", blinking = "Always" }
unfocused_hollow = true
blink_interval = 750

[keyboard]
bindings = [
    { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
    { key = "PageUp", mods = "Shift", action = "ScrollPageUp" },
    { key = "PageDown", mods = "Shift", action = "ScrollPageDown" },
    { key = "End", mods = "Shift", action = "ScrollToBottom" },
    { key = "Home", mods = "Shift", action = "ScrollToTop" },
]

[debug]
persistent_logging = false

